config/routes.rb
Template::Application.routes.draw do

  scope 'administration' do
    resources :contents
    resources :questions do
      post :sort, on: :collection
      resources :answers
    end
    resources :answers
    resources :about_sections
    resources :posts
    resources :subscriptions
    resources :judges
    resources :attachments
    resources :mentors
    resources :contacts
    resources :events
  end
  
  match "/administration" => "pages#admin", :as => "admin" #"user_root"
  match "/auth/:provider/callback" => "pages#external_auth"
  #match "/home" => "pages#index", :as => "website"
  match "/contact" => "pages#contact"
  match '/mail' => 'pages#send_mail', :as => :email, :via => :post
  match '/faq' => "pages#faq"
  match "/accept-answer" => "pages#accept_answer"
  match '/about' => "pages#about"
  match '/news' => "pages#news"
  match '/article/:id' => "pages#article"
  match '/calendar' => "pages#calendar"
  match '/application' => "pages#application"
  match '/dashboard' => "pages#dashboard"
  
  get "pages/index"
  get "pages/administration"

  devise_for :users, :path => 'administration/account', :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}
  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "registrations#new"
    get "/administration/account/settings" => "registrations#edit"
  end
  resources :users
  #authenticated :user, lambda {|u| u.admin == true} do
  #  root :to => "pages#admin", :as => :admin_root
  #  match "/home" => "pages#index", :as => "website"
  #end
  
  root :to => "pages#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/about_section.rb
class AboutSection < ActiveRecord::Base
  attr_accessible :active, :content, :section, :title, :logo
  has_attached_file :logo
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :accepted, :content, :question_id, :votes
  belongs_to :question, :foreign_key => "question_id"
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :note, :attached_file
  has_attached_file :attached_file
  
  def has_image
    %w(.png .jpg .jpeg .gif .bmp).include? File.extname(self.attached_file.path)
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :name, :organization, :phone
end

app/models/content.rb
class Content < ActiveRecord::Base
  attr_accessible :body, :name, :title, :published
  validates_uniqueness_of :name
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :event_date, :event_description, :event_name, :event_end, :location, :in_footer
  def start_time
    event_date.to_s
  end
  def end_time
    event_end.to_s
  end
  def name
    event_name
  end
  def link
    "/calendar?month=#{self.event_date.strftime("%-m")}&year=#{self.event_date.strftime("%Y")}"
  end
  def description
    event_description
  end
end

app/models/judge.rb
class Judge < ActiveRecord::Base
  attr_accessible :name, :organization, :sector, :title, :user_id
  belongs_to :user
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  attr_accessible :name, :organization, :sector, :title, :user_id
  belongs_to :user
end

app/models/message.rb
class Message
    include ActiveAttr::Model
    include ActiveModel::Validations

    attribute :email
    attribute :body
    attribute :subject
    #attr_accessible :email, :body, :subject

    validates_presence_of :email
    validates :email, :email_format => { :message => "Not a valid email address"}

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :active, :content, :section, :title
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answered, :content, :title, :votes, :row_order, :row_order_position
  has_many :answers
  include RankedModel
  ranks :row_order
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :email, :fname, :lname, :group_name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin, :google_access_token, :google_refresh_token, :google_expires_at, :label, :team
  # attr_accessible :title, :body
  has_one :judge
  has_one :mentor
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_filter :set_class, :authorize_or_redirect
  # GET /mentors
  # GET /mentors.json
  def index
    @mentors = Mentor.find(:all, :order => "name asc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mentors }
    end
  end

  # GET /mentors/1
  # GET /mentors/1.json
  def show
    @mentor = Mentor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mentor }
    end
  end

  # GET /mentors/new
  # GET /mentors/new.json
  def new
    @mentor = Mentor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mentor }
    end
  end

  # GET /mentors/1/edit
  def edit
    @mentor = Mentor.find(params[:id])
  end

  # POST /mentors
  # POST /mentors.json
  def create
    @mentor = Mentor.new(params[:mentor])

    respond_to do |format|
      if @mentor.save
        format.html { redirect_to mentors_path, notice: 'Mentor was successfully created.' }
        format.json { render json: @mentor, status: :created, location: @mentor }
      else
        format.html { render action: "new" }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mentors/1
  # PUT /mentors/1.json
  def update
    @mentor = Mentor.find(params[:id])

    respond_to do |format|
      if @mentor.update_attributes(params[:mentor])
        format.html { redirect_to mentors_path, notice: 'Mentor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentors/1
  # DELETE /mentors/1.json
  def destroy
    @mentor = Mentor.find(params[:id])
    @mentor.destroy

    respond_to do |format|
      format.html { redirect_to mentors_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def set_class
    @bodyclass = "admin admin-page"
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/judges_helper.rb
module JudgesHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/mentors/_form.html.erb
<%= simple_form_for(@mentor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :title %>
    <%= f.input :organization %>
    <%= f.input :sector %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/mentors/edit.html.erb
<%= render :partial => "layouts/admin_header" %>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1>Editing mentor</h1>
      <div class='admin-form'>
        <%= render 'form' %>
      </div>
      <%= link_to 'Back', mentors_path %>
    </div>
  </div>
</div>

app/views/mentors/index.html.erb
<%= render :partial => "layouts/admin_header" %>
<h1>Listing mentors</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Organization</th>
    <th>Sector</th>
    <th>Account</th>
    <th></th>
    <th></th>
  </tr>

<% @mentors.each do |mentor| %>
  <tr>
    <td><%= mentor.name %></td>
    <td><%= mentor.title %></td>
    <td><%= mentor.organization %></td>
    <td><%= mentor.sector %></td>
    <td><%= mentor.user.blank? ? "None" : mentor.user.email %></td>
    <td><%= link_to 'Edit', edit_mentor_path(mentor) %></td>
    <td><%= link_to 'Destroy', mentor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New mentor', new_mentor_path %>

app/views/mentors/new.html.erb
<%= render :partial => "layouts/admin_header" %>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1>New mentor</h1>
      <div class='admin-form'>
        <%= render 'form' %>
      </div>
      <%= link_to 'Back', mentors_path %>
    </div>
  </div>
</div>

app/views/mentors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mentor.name %>
</p>

<p>
  <b>Title:</b>
  <%= @mentor.title %>
</p>

<p>
  <b>Organization:</b>
  <%= @mentor.organization %>
</p>

<p>
  <b>Sector:</b>
  <%= @mentor.sector %>
</p>


<%= link_to 'Edit', edit_mentor_path(@mentor) %> |
<%= link_to 'Back', mentors_path %>